region_name = "us-west1"
zone_name = "us-west1-b"
machine_size = "f1-micro"
image_name = "ubuntu-os-cloud/ubuntu-1804-bionic-v20190403"
script_path = "./src/cloud-init.sh"
private_key_path = "~/.ssh/id_rsa"
public_key_path = "~/.ssh/id_rsa.pub"
username = "ubuntu"